INFO    : Found entry no longer exists 296887
INFO    : Now preparing local server to preview your project directory `/home/GitHub/cpge-eqdiff`.
INFO    :   (Reminder: use `pretext deploy` to deploy your built project to a public
INFO    :   GitHub Pages site that can be shared with readers who cannot access your
INFO    :   personal computer.)
INFO    : 
INFO    : starting server ...
INFO    : setting up ...
INFO    : values set...
WARNING : Port 8128 could not be used.
WARNING : Trying port 8129 instead.

WARNING : Port 8129 could not be used.
WARNING : Trying port 8130 instead.

INFO    : adding server entry
INFO    : There are 10 or more servers on file. Cleaning up ...
INFO    : Found entry no longer exists 2275953
INFO    : Terminating 2275953
INFO    : Terminate failed for 2275953.
ERROR   : process PID not found (pid=2275953)
Traceback (most recent call last):
  File "/home/mxbouja/.local/pipx/venvs/pretext/lib/python3.11/site-packages/pretext/server.py", line 76, in terminate
    psutil.Process(self.pid).terminate()
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mxbouja/.local/pipx/venvs/pretext/lib/python3.11/site-packages/psutil/__init__.py", line 317, in __init__
    self._init(pid)
  File "/home/mxbouja/.local/pipx/venvs/pretext/lib/python3.11/site-packages/psutil/__init__.py", line 363, in _init
    raise NoSuchProcess(pid, msg=msg) from None
psutil.NoSuchProcess: process PID not found (pid=2275953)
ERROR   : View encountered an error.  Please report this: process 14021 with laddr 
ERROR   : View encountered an error.  Please report this: process 14021 with laddr 
INFO    : Found server at localhost:8128
ERROR   : View encountered an error.  Please report this: process 15210 with laddr 
INFO    : Found server at localhost:8129
INFO    : Found entry no longer exists 296887
INFO    : Terminating 296887
INFO    : Terminate failed for 296887.
ERROR   : process PID not found (pid=296887)
Traceback (most recent call last):
  File "/home/mxbouja/.local/pipx/venvs/pretext/lib/python3.11/site-packages/pretext/server.py", line 76, in terminate
    psutil.Process(self.pid).terminate()
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mxbouja/.local/pipx/venvs/pretext/lib/python3.11/site-packages/psutil/__init__.py", line 317, in __init__
    self._init(pid)
  File "/home/mxbouja/.local/pipx/venvs/pretext/lib/python3.11/site-packages/psutil/__init__.py", line 363, in _init
    raise NoSuchProcess(pid, msg=msg) from None
psutil.NoSuchProcess: process PID not found (pid=296887)
INFO    : Found entry no longer exists 296887
INFO    : Terminating 296887
INFO    : Terminate failed for 296887.
ERROR   : process PID not found (pid=296887)
Traceback (most recent call last):
  File "/home/mxbouja/.local/pipx/venvs/pretext/lib/python3.11/site-packages/pretext/server.py", line 76, in terminate
    psutil.Process(self.pid).terminate()
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mxbouja/.local/pipx/venvs/pretext/lib/python3.11/site-packages/psutil/__init__.py", line 317, in __init__
    self._init(pid)
  File "/home/mxbouja/.local/pipx/venvs/pretext/lib/python3.11/site-packages/psutil/__init__.py", line 363, in _init
    raise NoSuchProcess(pid, msg=msg) from None
psutil.NoSuchProcess: process PID not found (pid=296887)
INFO    : Found entry no longer exists 296887
INFO    : Terminating 296887
INFO    : Terminate failed for 296887.
ERROR   : process PID not found (pid=296887)
Traceback (most recent call last):
  File "/home/mxbouja/.local/pipx/venvs/pretext/lib/python3.11/site-packages/pretext/server.py", line 76, in terminate
    psutil.Process(self.pid).terminate()
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mxbouja/.local/pipx/venvs/pretext/lib/python3.11/site-packages/psutil/__init__.py", line 317, in __init__
    self._init(pid)
  File "/home/mxbouja/.local/pipx/venvs/pretext/lib/python3.11/site-packages/psutil/__init__.py", line 363, in _init
    raise NoSuchProcess(pid, msg=msg) from None
psutil.NoSuchProcess: process PID not found (pid=296887)
INFO    : Found entry no longer exists 296887
INFO    : Terminating 296887
INFO    : Terminate failed for 296887.
ERROR   : process PID not found (pid=296887)
Traceback (most recent call last):
  File "/home/mxbouja/.local/pipx/venvs/pretext/lib/python3.11/site-packages/pretext/server.py", line 76, in terminate
    psutil.Process(self.pid).terminate()
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mxbouja/.local/pipx/venvs/pretext/lib/python3.11/site-packages/psutil/__init__.py", line 317, in __init__
    self._init(pid)
  File "/home/mxbouja/.local/pipx/venvs/pretext/lib/python3.11/site-packages/psutil/__init__.py", line 363, in _init
    raise NoSuchProcess(pid, msg=msg) from None
psutil.NoSuchProcess: process PID not found (pid=296887)
INFO    : Found entry no longer exists 296887
INFO    : Terminating 296887
INFO    : Terminate failed for 296887.
ERROR   : process PID not found (pid=296887)
Traceback (most recent call last):
  File "/home/mxbouja/.local/pipx/venvs/pretext/lib/python3.11/site-packages/pretext/server.py", line 76, in terminate
    psutil.Process(self.pid).terminate()
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mxbouja/.local/pipx/venvs/pretext/lib/python3.11/site-packages/psutil/__init__.py", line 317, in __init__
    self._init(pid)
  File "/home/mxbouja/.local/pipx/venvs/pretext/lib/python3.11/site-packages/psutil/__init__.py", line 363, in _init
    raise NoSuchProcess(pid, msg=msg) from None
psutil.NoSuchProcess: process PID not found (pid=296887)
INFO    : Found entry no longer exists 296887
INFO    : Terminating 296887
INFO    : Terminate failed for 296887.
ERROR   : process PID not found (pid=296887)
Traceback (most recent call last):
  File "/home/mxbouja/.local/pipx/venvs/pretext/lib/python3.11/site-packages/pretext/server.py", line 76, in terminate
    psutil.Process(self.pid).terminate()
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mxbouja/.local/pipx/venvs/pretext/lib/python3.11/site-packages/psutil/__init__.py", line 317, in __init__
    self._init(pid)
  File "/home/mxbouja/.local/pipx/venvs/pretext/lib/python3.11/site-packages/psutil/__init__.py", line 363, in _init
    raise NoSuchProcess(pid, msg=msg) from None
psutil.NoSuchProcess: process PID not found (pid=296887)
ERROR   : View encountered an error.  Please report this: process 609299 with laddr 
ERROR   : View encountered an error.  Please report this: process 609299 with laddr 
ERROR   : View encountered an error.  Please report this: process 609299 with laddr 
INFO    : Found server at localhost:8130
INFO    : Added server entry 7586deee7e 609299 8130 localhost

INFO    : Starting the server
INFO    : Server will soon be available at http://localhost:8130
INFO    : Opening browser for target `web` at http://localhost:8130/output/web
